sudo: required
language: generic
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
script:
  - docker run --rm --privileged multiarch/qemu-user-static:register
  - docker build --tag="thebiggerguy/mono-issue-9788" .
  - ulimit -c unlimited
  - docker run --cap-add="SYS_PTRACE" -v "${PWD}:/tmp" thebiggerguy/mono-issue-9788
  - sudo cat mono-gdb-commands.*